site_name: Pyes Documentation
site_url: https://pyes.dev

nav:
  - Home: index.md
  - About:
    - "Intro": about/intro.md
    - "Why Pyes":
      - "Why": about/why/why.md
      - "Core Concepts": about/why/core_concepts.md
      - "No, but why": about/why/actually_why.md
  - Basics:
    - "Variables": basics/variables.md
    - "Types": basics/types.md
    - "Generics": basics/generics.md
  - Primitives:
    - "Number": primitives/number.md
    - "String": primitives/string.md
    - "Boolean": primitives/boolean.md
  - Data Structures:
    - "Array": data_structures/array.md
    - "Map": data_structures/map.md
    - "Struct": data_structures/struct.md

theme:
  name: material

markdown_extensions:
  - attr_list

  # Emojis support
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  # Code block syntax highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
